version: 0.2
phases:
  install:
    runtime-versions:
      ruby: 2.7
    commands:
      - bundle install --gemfile=jekyll/Gemfile
  build:
    commands:
      - cd jekyll
      - JEKYLL_ENV=production bundle exec jekyll build
artifacts:
    base-directory: 'jekyll/_site'
    files:
      - '**/*'